name: Greetings

on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Sample Json
      id: sample_json
      run: |
            echo "packageJson='{\"a\":\"123\"}'" >> "$GITHUB_OUTPUT"
            
    - name: Extract Json
      id: extact_json
      run: |
            echo "${steps.sample_json.outputs.packageJson}"
